CREATE TABLE IF NOT EXISTS TOKEN_ENTRY
(
    PROCESSOR_NAME VARCHAR(255) NOT NULL,
    SEGMENT        INTEGER      NOT NULL,
    TOKEN          BLOB,
    TOKEN_TYPE     VARCHAR(255),
    TIMESTAMP      VARCHAR(255),
    OWNER          VARCHAR(255),
    PRIMARY KEY (PROCESSOR_NAME, SEGMENT)
);
