-- The pgvector extension is required by Spring AI's vector store. The compose
-- init script already enables it; keeping it here makes the migration self-sufficient.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE documents (
    id BIGINT NOT NULL,
    source VARCHAR(255),
    type VARCHAR(255),
    content TEXT,
    domain VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE ai_application_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    level VARCHAR(20),
    message TEXT,
    exception TEXT,
    correlation_id VARCHAR(64)
);

CREATE TABLE healing_recommendation (
    recommendation_id VARCHAR(255) NOT NULL,
    symptom_id VARCHAR(255),
    problem VARCHAR(255),
    severity VARCHAR(255),
    root_cause VARCHAR(255),
    evidence TEXT,
    suggested_action VARCHAR(255),
    confidence INTEGER,
    requires_human_approval BOOLEAN,
    status VARCHAR(255),
    version BIGINT NOT NULL,
    created_at TIMESTAMP,
    PRIMARY KEY (recommendation_id)
);
