package com.ravi.eventmind.command.healing.aggregate;

import com.ravi.eventmind.shared.commands.CreateHealingRecommendationCommand;
import com.ravi.eventmind.shared.events.HealingRecommendationCreatedEvent;
import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import org.axonframework.modelling.command.AggregateLifecycle;
import org.axonframework.spring.stereotype.Aggregate;

import java.util.UUID;

@Aggregate
public class HealingRecommendationAggregate {

    @AggregateIdentifier
    private String symptomId;
    private String healingAction;
    private double confidenceScore;
    private String status;

    // Axon requires a default constructor
    protected HealingRecommendationAggregate() {}

    // 1. Catch the Command sent from your AiCommandListener!
    @CommandHandler
    public HealingRecommendationAggregate(CreateHealingRecommendationCommand command) {
        // Enforce invariants (e.g., don't accept empty recommendations)
        if (command.healingAction() == null || command.healingAction().isBlank()) {
            throw new IllegalArgumentException("Healing action generated by AI cannot be empty.");
        }

        // Apply and publish the event into the immutable Axon Event Log
        AggregateLifecycle.apply(new HealingRecommendationCreatedEvent(
                command.symptomId(),
                command.healingAction(),
                command.confidenceScore(),
                command.status()
        ));
    }

    // 2. Handle the Event to set the state in-memory
    @EventSourcingHandler
    public void on(HealingRecommendationCreatedEvent event) {
        this.symptomId = event.symptomId();
        this.healingAction = event.healingAction();
        this.confidenceScore = event.confidenceScore();
        this.status = event.status(); // Will be "PENDING_APPROVAL"
    }
}

