spring:
  application:
    name: eventmind-command

  config:
    import: optional:file:../.env[.properties]

server:
  port: 8081

axon:
  axonserver:
    enabled: true
    servers: ${AXON_AXONSERVER_SERVERS:localhost:8124}
  distributed:
    enabled: false
  serializer:
    general: jackson
    events: jackson
